[package]
name = "vpm"
version = "0.1.0"
edition = "2021"
authors = ["Lily Smart <lily@neyoa.me>"]
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
colored = "2.1.0"
libc = "0.2.162"
